aspnet/MetaPackages

src/Microsoft.AspNetCore/Microsoft.AspNetCore.csproj

By default, pack sets `PrivateAssets="Build,Analyzers"`, which means the metapackage would not import targets from any of the packages listed here.
Changes the generated nuspec from:
```xml
<dependency id="Microsoft.AspNetCore.Diagnostics" version="1.2.0-preview1-23373" exclude="Build,Analyzers" />
```
to
```xml
<dependency id="Microsoft.AspNetCore.Diagnostics" version="1.2.0-preview1-23373" include="All" />
```
None of them do...yet...but we'll need this for MvcPrecompliation.

Set references to PrivateAssets=None

---

MetaPackages.sln
build/common.props
build/dependencies.props
build/repo.targets
src/Microsoft.AspNetCore.All/Microsoft.AspNetCore.All.csproj

Add Microsoft.AspNetCore.All metapackage and build package cache

---

src/Microsoft.AspNetCore.All/Microsoft.AspNetCore.All.csproj
src/Microsoft.AspNetCore.All/build/PublishWithAspNetCoreTargetManifest.targets
src/Microsoft.AspNetCore.All/build/netstandard1.6/Microsoft.AspNetCore.All.targets

#20 
Adding this target to set target manifest used before publish based on the current OS and Platform. The actual manifest.RID.xml will be added to this package during the build when it's generated by dotnet store. For cross-publish scenarios, `AspNetCoreTargetManifestRuntimeIdentifier` can be set in the project. `PublishWithAspNetCoreTargetManifest` can be set to false to publish without manifest.

Add target to set default target manifest

---

build/repo.targets

This is breaking package cache generation on xplat. Not sure if I can use System.IO.Path.DirectorySeparatorChar instead though.

Platform specific path separator

---

build/common.props
samples/SampleApp/Program.cs
samples/SampleApp/SampleApp.csproj
samples/SampleApp/wwwroot/htmlpage.html
src/Microsoft.AspNetCore/WebHost.cs

#24 following up to more issues.
- Specify ApplicationName when wrapping RequestDelegate or RouteBuilder
- Add debug logger by default
Still need to add tests.

WebHost static API updates

---

MetaPackages.sln
build/common.props
src/Microsoft.AspNetCore.RuntimeStore/Microsoft.AspNetCore.RuntimeStore.csproj

The build system is a little finicky when we want to build the runtime store with a reference to Microsoft.AspNetCore.
`dotnet store` will only operate on PackageReference and not ProjectReference. Having a PackageReference from Microsoft.AspNetCore.RuntimeStore to Microsoft.AspNetCore creates a cyclic dependency when building Universe. 
The simplest solution to achieve what we want is to remove the RuntimeStore project from the solution. This way it's not being restored/built during Universe-Coherence and there is no cyclic dependency. When we build the runtime store, it will have a PackageReference to the Microsoft.AspNetCore package in the drops share.

Remove runtime store from sln

---

src/Microsoft.AspNetCore.All/build/PublishWithAspNetCoreTargetManifest.targets

Fixes #50 
It's too late to set the `TargetManifestFiles` property inside a target that runs before publish. The dotnet sdk publish targets resolve the file list [here](https://github.com/dotnet/sdk/blob/39102ec214514363c6af4cd9d599a35aceb8c745/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.Publish.targets#L32-L34). Since we don't rely on any other targets or properties to set `TargetManifestFiles`, the proposal in thiss PR sets the property in a property group before the donet sdk publish targets. Note that in this approach we no longer produce an error if the resolution of the manifest rid fails and will fail silently instead.
I tested on a local dotnet new console app with a package reference to M.A.All package and the publish output is trimmed.

Set TargetManifestFiles in PropertyGroup

---

build/common.props
build/dependencies.props

Because we are not shipping SignalR in 2.0

Remove SignalR from .All MetaPackage and RuntimeStore

---

src/Microsoft.AspNetCore.All/build/PublishWithAspNetCoreTargetManifest.targets

Trim with all manifests

---

build/repo.targets

This fixes the rel/2.0.0-preivew1 build of Coherence-PackageCache

Clean up before AddManifestToNupkg

---

src/Microsoft.AspNetCore/WebHost.cs

Fixes: https://github.com/aspnet/MetaPackages/issues/58
/cc @DamianEdwards

Validate scopes in Development environment in CreateDefaultBuilder

---

build/repo.targets
src/Microsoft.AspNetCore.All/build/PublishWithAspNetCoreTargetManifest.targets

Simplify the script to now build one runtime store per CI configuration. Also fix a few bugs and use the new consolidated RIDs.

Build one zip per configuration

---

build/common.props
src/Microsoft.AspNetCore.All/Microsoft.AspNetCore.All.csproj

Addressing a few packages left behind in #21
Packages to add:
The Scaffolding packages cannot be added right now due to https://github.com/dotnet/roslyn/issues/16040

Add more packages

---

build/Build.RS.nuspec

After https://github.com/aspnet/Coherence-Signed/pull/478 we need to include .tar.gz files in the Build.RS nupkg. 
Note that this package is used mainly for testing with JitBench on x-plat. cc @rynowak This is not blocking installer work since they obtain the stores from the drop share.
cc @muratg to decide whether this should go into rel/2.0.0-preview1 or only dev.

Include tar.gz files in Build.RS nupkg

---

build/repo.targets

This should fix the CI package cache build flakiness.
cc @kichalla @danroth27

Minimal restore when building deps files

---

build/repo.targets

We should be building the store witn win7-x64 and win7-x86 rids instead of win-x64 and win-x86 rids.
We should also verify that linux-x64 and osx-x64 are sufficient for the xplat runtime stores. It would be a dramatic change if we build one for each possible platform.
cc @DamianEdwards @davidfowl

Use win7-x64/x86 rids for runtime store

---

build/common.props
src/Microsoft.AspNetCore.All/Microsoft.AspNetCore.All.csproj

I think this increases the readability of the list. Also makes it more obvious when a package deviates from the default values, i.e. packages usage AspNetCoreIdentityServiceVersion instead of AspNetCoreVersion
See https://docs.microsoft.com/en-us/visualstudio/msbuild/item-definitions

Use ItemDefinitionGroup to simplify the list of packages.

---

build/repo.targets

On xplat we get the errors:
```
[22:16:02] :	 [Step 2/3]   /bin/sh: 2: /home/aspnetagent/buildAgent/temp/buildTmp/tmpa9c3d29b9bfb485898a17a111e61e096.exec.cmd: Rebuild: not found
[22:16:02] :	 [Step 2/3]   /bin/sh: 2: /home/aspnetagent/buildAgent/temp/buildTmp/tmpa9c3d29b9bfb485898a17a111e61e096.exec.cmd: CollectDeps: not found
```
Which means deps files are not generated. The next step then fails when we try to remove timestamps from those files.

Fix generation of deps files on macOS and Linux

---

MetaPackages.sln
test/Microsoft.AspNetCore.FunctionalTests/WebHostFunctionalTests.cs
test/TestSites/DependencyInjectionApp/DependencyInjectionApp.csproj
test/TestSites/DependencyInjectionApp/Program.cs

Fixes: https://github.com/aspnet/MetaPackages/issues/72

Add test for DI scope validation defaults

---

build/repo.targets
src/Microsoft.AspNetCore.All/Microsoft.AspNetCore.All.csproj
src/Microsoft.AspNetCore.All/build/PublishWithAspNetCoreTargetManifest.targets

Addresses #124 to clarify which manifests are problematic when error message is displayed.

Update manifest names

---

build/common.props
build/dependencies.props
samples/SampleApp/SampleApp.csproj
src/Microsoft.AspNetCore/CertificateLoader.cs
src/Microsoft.AspNetCore/Microsoft.AspNetCore.csproj
src/Microsoft.DotNet.Archive/Microsoft.DotNet.Archive.csproj
test/Microsoft.AspNetCore.FunctionalTests/Microsoft.AspNetCore.FunctionalTests.csproj
test/Microsoft.AspNetCore.Tests/Microsoft.AspNetCore.Tests.csproj

Note a few caveats in this repo is a bit different. 
The only package we need to convert to NStandard2.0 is Microsoft.AspNetCore. M.A.All stays as netcoreapp2.0. 
The tests are a little misleading since there are functional and unit tests in the FunctionalTest project. I've added the net461 TFM to the FuntionalTests so that the unit tests are tested on both platforms. I'll file a follow up issue to split the functional and unit tests and also add coverage for .NET Framework variations for the functional tests.

Target NETStandard2.0

---

build/common.props

Per https://github.com/NuGet/Home/issues/5233, we need to mark everything that transitively depends on sqlitepclraw as PrivateAssets="Build". I took a look a the EF packages and it seems like they don't have any build assets them selves so this should be safe. I have verified that this workaround works and the sqlite native binaries no longer shows up in the publish output. Will need to update buildtools with the new third-party dependencies.
There is discussion with regards to whether the changes in https://github.com/dotnet/sdk/pull/1133 will be changed and the net461 PackageTargetFallback removed so this may no longer be relevant. However, in the meantime, we can use this workaround to trim the publish output.

Exclude build assets from sqlitepclraw and dependencies

---

build/repo.targets

Currently I see the error
```
Unable to load Microsoft.DiaSymReader.Native.amd64.dll.  Please ensure that Microsoft.DiaSymReader.Native.amd64.dll is on the path.  Error='126'
Error generating PDB for 'C:\gh\MetaPackages2\src\Microsoft.AspNetCore.RuntimeStore\bin\work\Build.RuntimeStore.References_2.0.0-preview2--\runtimopt\SQLitePCLRaw.core.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
```
when running dotnet store. This will unblock the build until I figure out what is going on.
cc @mikeharder @ryanbrandenburg

Skip symbol generation during runtime store creation

---

build/repo.targets
tools/Build.RuntimeStore.References/Build.RuntimeStore.References.csproj

Consolidating the individual package references into a separate project and referencing that in the runtime store project reduces the build time ~90%.

Faster runtime store build

---

.gitignore
build/repo.targets
tools/GetSharedFrameworkVersion.ps1
tools/zip2tgz.sh

By adding Microsoft.DiaSymReader.Native.*.dll to the path
Addresses #135 
Blocked on errors:
```
Error generating PDB for 'C:\gh\MetaPackages2\src\Microsoft.AspNetCore.RuntimeStore\bin\work\Build.RuntimeStore.References_2.0.0-preview2--\runtimopt\Microsoft.Extensions.Hosting.Abstractions.dll': Unspecified error (Exception from HRESULT: 0x80004005 (E_FAIL))
EXEC : error : compilation failed for "C:\gh\MetaPackages2\src\Microsoft.AspNetCore.RuntimeStore\bin\work\Build.RuntimeStore.References_2.0.0-preview2--\runtimopt\Microsoft.Extensions.Hosting.Abstractions.dll" (0x80004005) [C:\gh\MetaPackages2\src\Microsoft.AspNetCore.RuntimeStore\bin\work\Restore.csproj] [C:\gh\MetaPackages2\.build\KoreBuild.proj]
C:\Users\johluo\.dotnet\x64\sdk\2.0.0-preview2-006215\Sdks\Microsoft.NET.Sdk\build\Microso …
```

Re-enable building symbols for runtime store

---

build/repo.targets

No symbols are generated for macOS
Add environment variable to pass additional arguments to dotnet store

Fix PackageCache builds

---

build/repo.targets

MSBuild doesn't seem to update environment variables when called through MSBuild Target. The env vars will update when the target is called from DependsOnTargets.

Update DiaSymReader path update

---

build/dependencies.props
build/repo.targets
tools/RestoreRuntimeStore/NuGet.config
tools/RestoreRuntimeStore/RestoreRuntimeStore.csproj
tools/debian_config.json
tools/docker/debian/Dockerfile
tools/docker/ubuntu.14.04/Dockerfile
tools/docker/ubuntu.16.04/Dockerfile
tools/docker/ubuntu.16.10/Dockerfile
tools/dotnet-deb-tool-consumer/NuGet.config
tools/dotnet-deb-tool-consumer/dotnet-deb-tool-consumer.csproj

Addresses https://github.com/aspnet/MetaPackages/issues/149

Debian installers

---

build/common.props

Resolves most restore warnings about Microsoft.Composition. (There is still one coming from Archive.AspNetCore.All)
These references were essentially a no-op because they are not in the final Microsoft.AspNetCore.All package and are not in the runtime store.
cc @mikeharder @prafullbhosale

Remove scaffolding packages

---

build/repo.targets
src/Microsoft.AspNetCore.All/Microsoft.AspNetCore.All.csproj
src/Microsoft.AspNetCore.All/build/PublishWithAspNetCoreTargetManifest.targets

We are running into an issue where the store generated on windows and non-windows are different. The windows stores (x86 and x64) do not contain the M.A.Mvc.Razor.ViewCompilation while the non windows store (macOS and linux) do not. Our assumption that the stores on all platforms are the same is now broken so our approach of trimming by all manifests no longer works. We need to react accordingly in the M.A.All metapackage target and the proposal is to remove the ViewCompilation entry from the manifest so it will never be trimmed.
This would resolve https://github.com/aspnet/MvcPrecompilation/issues/146, note that after preview2 we plan to remove ViewCompilation from the runtime store so this will not be an issue for the next release.
I also ported the fix from …

Remove ViewCompilation from publish manifest

---

build/repo.targets
tools/debian_config.json

As per discussion in https://github.com/aspnet/MetaPackages/pull/163#discussion_r123053769. This seems to be the more appropriate value for the license field since there is no other field to specify the version of the Apache license and the common licenses lists this specific value.

Set license to Apache 2.0

---

build/repo.targets

Internal.AspnetCore.Sdk should only be used in \*.csproj files, not repo.targets. Because repo.targets imports common.props, it ends up with a reference with this package, which is causing build failures due to changes in Internal.AspNetCore.BuildTools.Tasks.

Workaround issue caused by importing Internal.AspNetCore.Sdk into repo.targets

---

src/Microsoft.AspNetCore.All/Microsoft.AspNetCore.All.csproj

Resolves #142 
When installing to net461, it will be incompatible:

Ensure Microsoft.AspNetCore.All is only compatible with netcoreapp2.0

---

build/repo.targets

Addresses https://github.com/aspnet/MetaPackages/issues/155. 
This will allow our builds to pick up the latest archives from Coherence-Signed instead of relying on myget which tends to pick up older builds due to lag in indexing.

Use specified signed runtime store archives when available for installers

---

src/Microsoft.AspNetCore.All/build/PublishWithAspNetCoreTargetManifest.targets

Addresses https://github.com/aspnet/MetaPackages/issues/175. 
We will inspect this property instead of RuntimeIdentifier/RuntimeIdentifiers to determine whether the TargetManifestFiles should be updated. This new property is set in the sdk: https://github.com/dotnet/sdk/blob/43090565482d9a10481ff2298fb168fc819fa430/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.RuntimeIdentifierInference.targets#L107-L110
Still needs to be tested before being reviewed.

Use new SelfContained property

---

build/repo.targets
build/tasks/CreateCommonManifest.cs
build/tasks/RepoTasks.csproj
build/tasks/RepoTasks.tasks
tools/Build.RuntimeStore.References/Build.RuntimeStore.References.csproj

Addresses: https://github.com/aspnet/MetaPackages/issues/172
This will trim additional packages such as runtime.win-arm64.runtime.native.system.data.sqlclient.sni

Create common manifest file

---

build/repo.targets

Following up to https://github.com/aspnet/Coherence-Signed/pull/611.
This ensures the store, deps files, installers and lzma have the correct no-timestamp versions.

Update no-timestamp versions

---

build/dependencies.props

Merging now to unblock. We need to keep this version in sync with korebuild and figure out what the actual problem is since pinning shouldn't be needed.

Pin runtime version for generated deps files

---

build/dependencies.props
build/repo.targets
tools/GetSharedFrameworkVersion.sh

This should fix the runtime versions for the deps files generated for the store

Use installed shared framework version during deps file generation

---

build/dependencies.props

This property isn't needed anymore, but I'm mostly making this PR in the hopes that it refreshes TeamCity's git cache.

Remove NETStandardLibraryNETFrameworkVersion

---

build/repo.targets

This allows me to use a custom dotnet-install that skips the installation of the 1.0.5/1.1.2 runtime on certain platforms during the build on ubuntu.16.10.

Use custom KoreBuild and dotnet-install if specified

---

build/dependencies.props
test/Microsoft.AspNetCore.FunctionalTests/WebHostFunctionalTests.cs

This is a reaction to the Kestrel change https://github.com/aspnet/KestrelHttpServer/pull/2186 where kestrel listens on https://localhost:5001 by default if the dev cert is present. The dev cert is present on these agents but is not trusted. Trust cannot be established in an automated fashion, so we disable the trust check.
If this has a wider impact we can reconsider moving this functionality into the hosting test infrastructure, but these were the only failures in Universe.

Allow untrusted certs in tests

---

samples/SampleApp/appsettings.json
src/Microsoft.AspNetCore/WebHost.cs
test/Microsoft.AspNetCore.FunctionalTests/WebHostFunctionalTests.cs
test/TestSites/CreateDefaultBuilderApp/appsettings.json

Kestrel now supports config, but it doesn't read any by default. CreateDefaultBuilder will specify the default location of the Kestrel config section. @DamianEdwards, @danroth27 asked if this config section should be namespaced as "Microsoft:Kestrel" or if a top level "Kestrel" section was ok?
I've also updated an old appsettings.json sample with the new config schema.
See https://github.com/aspnet/KestrelHttpServer/pull/2186

Add kestrel config to CreateDefaultBuilder

---

test/Microsoft.AspNetCore.FunctionalTests/WebHostFunctionalTests.cs
test/TestSites/CreateDefaultBuilderOfTApp/appsettings.json
test/TestSites/DependencyInjectionApp/Program.cs

The prior change did fix the invalid cert issue, but then some tests started failing only on net461 with an algorithm conflict. @javiercn you may want to check the default algorithms between a net461 client and a Core server.
Different fix: force these tests to use http.
Feel free to merge, I may be offline.

Force http in tests

---

build/dependencies.props
samples/SampleApp/appsettings.json
src/Microsoft.AspNetCore/HostFilteringStartupFilter.cs
src/Microsoft.AspNetCore/Microsoft.AspNetCore.csproj
src/Microsoft.AspNetCore/WebHost.cs
test/TestSites/CreateDefaultBuilderOfTApp/Startup.cs
test/TestSites/CreateDefaultBuilderOfTApp/appsettings.json

Damian didn't want this code in the template so we're putting it in the default builder instead.
https://github.com/aspnet/templating/pull/374
It will be disabled by default, it only lights up if you define AllowedHosts as a semicolon separated list in config.

Add HostFiltering to the default web host

---

test/TestSites/CreateDefaultBuilderApp/CreateDefaultBuilderApp.csproj
test/TestSites/CreateDefaultBuilderOfTApp/CreateDefaultBuilderOfTApp.csproj
test/TestSites/DependencyInjectionApp/DependencyInjectionApp.csproj
test/TestSites/StartRequestDelegateUrlApp/StartRequestDelegateUrlApp.csproj
test/TestSites/StartRouteBuilderUrlApp/StartRouteBuilderUrlApp.csproj
test/TestSites/StartWithIApplicationBuilderUrlApp/StartWithIApplicationBuilderUrlApp.csproj

These test have been failing since the 2.2 migration last Tuesday. IntegrationTesting's default TFM was changed from 2.0 to 2.2.

Fix tests failing after netcoreapp2.2 migration

---

build/dependencies.props
src/Microsoft.AspNetCore/WebHost.cs
test/Microsoft.AspNetCore.FunctionalTests/WebHostFunctionalTests.cs
test/TestSites/CreateDefaultBuilderApp/Program.cs
test/TestSites/CreateDefaultBuilderOfTApp/Startup.cs

Fixes #267 and http://aspnetci/viewLog.html?buildId=474296&tab=buildResultsDiv&buildTypeId=Lite_UniverseTest
Honor ASPNETCORE_CONTENTROOT, and only set CurrentDirectory if no other value was provided.
I consolidated the config code for clarity.

 Do not overwrite ContentRoot

---

src/Microsoft.AspNetCore/WebHost.cs

This removes the documentation about the default configuration capabilities in the default web host builder. The feature was originally introduced in 4b18cf52ae3c22c7124fd9cb35ae0253b390b28e and soon unshipped in c920c459537c21285b47b05f033a48363297e3dc. However, the documentation that was added with it never got removed.
Since this is visible on [docs.microsoft.com](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.webhost.createdefaultbuilder?view=aspnetcore-2.0), we should probably fix that before more people look for features that aren’t there.
/cc @ctolkien

Remove doc about unshipped default configuration

---

version.props

This is required because the metapackage depends on IISIntegration. Per our latest design around how patches work, metapackages, including "Microsoft.AspNetCore", always patch if their transitive dependencies patch.

Bump version to 2.1.7
