NuGet.config, build.ps1, build.sh, makefile.shade, src/Microsoft.AspNetCore/project.json
=> 1.1.0 dependencies

src/Microsoft.AspNetCore/project.json
@pranavkm 
Merge to dev after push
=> Remove StaticFiles from AspNetCore meta package

src/Microsoft.AspNetCore/project.json
=> Target netcoreapp and reference NETCore.App

src/Microsoft.AspNetCore/project.json
=> Added tags to project.json

src/Microsoft.AspNetCore/project.json
=> Update reference versions

MetaPackages.sln, build/repo.targets
Merging immediately to try it out. Will address any feedback.
=> Generate package cache for each RID

build/repo.targets
Avoid using myget for restores due to lag.
=> Use dependencies when available

src/Microsoft.AspNetCore.All/Microsoft.AspNetCore.All.csproj
https://github.com/aspnet/Coherence/pull/193
=> Remove Microsoft.Extensions.Logging.Filter

build/common.props
This PR removes all references to PlatformAbstractions.
Part of aspnet/PlatformAbstractions#50
=> react to removal of PlatformAbstractions

build/common.props
See https://github.com/aspnet/Hosting/pull/1051
=> Add Microsoft.Extensions.Hosting.Abstractions

build/repo.targets, src/Microsoft.AspNetCore.RuntimeStore/Microsoft.AspNetCore.RuntimeStore.csproj
Addressing #52 
Also removing artifacts.xml from the runtime store zip.
This needs to be approved for rel/2.0.0-preview1
=> Zip store and deps together

build/Build.RuntimeStore.nuspec, build/repo.targets
Fix coherence-signed in rel/2.0.0-preview1
=> Long path woes

src/Microsoft.AspNetCore/WebHost.cs
Depends on https://github.com/aspnet/Configuration/pull/654
Resolves #60
=> AddUserSecrets is optional

NuGet.config, src/Archive.AspNetCore.All/Archive.AspNetCore.All.csproj
This adds the proper set of packages to the Package Archive list
=> use actual set of packages

NuGet.config, build/common.props, build/repo.targets, src/Archive.AspNetCore.All/Archive.AspNetCore.All.csproj, src/Microsoft.AspNetCore/WebHost.cs, src/dotnet-archive/dotnet-archive.csproj, test/Microsoft.AspNetCore.FunctionalTests/WebHostFunctionalTests.cs, test/TestSites/CreateDefaultBuilderApp/Program.cs
=> Add configuration to logging in WebHost

src/Microsoft.DotNet.Archive/IndexedArchive.cs, src/dotnet-archive/Program.cs, src/dotnet-archive/dotnet-archive.csproj
/cc @livarcocc - Since these changes are mostly in the code that came from your repo ;).
=> fix LZMA archive directory structure

build/common.props, build/dependencies.props, src/Microsoft.AspNetCore.All/Microsoft.AspNetCore.All.csproj
See #97 
This is a workaround that we should try to fix the right way.
=> 2.0.0-preview1- Set PrivateAssets=Build for SQLitePCl.bundle_green

src/Microsoft.AspNetCore.All/build/PublishWithAspNetCoreTargetManifest.targets
Missed rename update after RID change
=> Missed rename updates

tools/TrimDeps/Program.cs
=> Fix deps trimming

build/repo.targets
The logic was skipped since OSPlatform was empty.
=> Remove timestamps from deps files

build/repo.targets
This will fix the coherence-packagecache builds @ryanbrandenburg
=> React to dotnet store cli arguments update

src/Microsoft.AspNetCore/KestrelServerOptionsSetup.cs
When the ssl certificate specified is 'localhost' and
no certificate has been explicitly specified in the certificates
section, fallback to a certificate with 'CN=localhost' (ASP.NET Core SSL
developer certificate) in the current user store and if not found,
an ssl certificate with 'CN=localhost' on the current machine
(IIS Express developer certificate)
=> Add support for a default SSL certificate in development

build/common.props
=> Add HostingStartup packages to .All

build/common.props
- https://github.com/aspnet/EntityFramework/commit/778a8434444cd05fc5b52ea4de3c6bbb6f5e252d
- https://github.com/aspnet/EntityFramework/commit/32434d2d86a75e091e331940384115e447ff33de
- https://github.com/aspnet/EntityFramework/commit/73e10420f58bbaa65bc6b7321e98b791b56387ba
=> Remove Microsoft.EntityFrameworkCore.*.Design packages

build/common.props
#157 @muratg @HaoK @Eilon 
Preview2 blocking
=> Remove DockerSecrets

build/dependencies.props
React to https://github.com/aspnet/Microsoft.Data.Sqlite/pull/374
=> Revert to SQLitePCLRaw 1.1.3

build/repo.targets, tools/changelog, tools/docker/rhel/Dockerfile
=> Build RPM installers

build/common.props, build/dependencies.props
Take 2.
Reacting to: 
https://github.com/aspnet/BuildTools/pull/285
https://github.com/aspnet/Microsoft.Data.Sqlite/pull/378
https://github.com/aspnet/EntityFramework/pull/9006
=> Remove SQLitePCLRaw workaround

build/repo.targets, tools/changelog, tools/debian_config.json
Use the new `JsonPeek` task to parse common installer parameters from debian_config.json to reduce duplication. Tested manually.
=> Installer generation updates

build/dependencies.props, tools/TrimDeps/TrimDeps.csproj
- Matches other repos
@Eilon: `2.0` or `dev`?
=> Rename property to JsonNetVersion

src/Archive.AspNetCore.All/Archive.AspNetCore.All.csproj
=> Add M.Dotnet.Watcher.Tools and M.E.Caching.SqlConfig.Tools to lzma

build/repo.targets
This should fix coherence-signed.
=> ProjectPath is no longer set, use MSBuildThisFileFullPath instead

build.sh
Similar to https://github.com/aspnet/BuildTools/pull/352. This needs mass update?
=> Fix __get_remote_file logic

src/Microsoft.AspNetCore/baseline.netcore.json
https://github.com/aspnet/MetaPackages/issues/37
cc @ryanbrandenburg, apparently you are doing this for all the repos? Should I make this change or wait for yours?
=> Add API baseline for Microsoft.AspNetCore

build/repo.targets
I'll try to test this locally before I merge
=> Fix package archive name typo

MetaPackages.sln, build/SiteExtension.targets, build/repo.targets, src/Microsoft.AspNetCore.SiteExtension/Microsoft.AspNetCore.SiteExtension.csproj, src/Microsoft.AspNetCore.SiteExtension/applicationHost.xdt
I mostly want to merge zip fallback archive generation so I can test extension creation better and start putting it on CI.
=> Add site extension generation code

src/Microsoft.AspNetCore/WebHost.cs
#223 We no longer add developer exception pages via startup filters.
=> Update doc comments

build/dependencies.props
This is part of the templates work I'm doing.
=> Add back Identity service packages to the meta package

build/dependencies.props
=> Add Microsoft.Extensions.Hosting

MetaPackages.sln, samples/SampleApp/Program.cs, src/Microsoft.AspNetCore/WebHost.cs, test/Microsoft.AspNetCore.Tests/Microsoft.AspNetCore.Tests.csproj, test/Microsoft.AspNetCore.Tests/WebHostTests.cs
=> Populate WebHost configuration with command line arguments if provided

src/Microsoft.AspNetCore/WebHost.cs, test/Microsoft.AspNetCore.Tests/WebHostTests.cs
The second half of https://github.com/aspnet/BasicMiddleware/pull/320. There's no direct dependency between these, they can be checked in independently.
=> Reload HostFilteringOptions on change

src/Microsoft.AspNetCore/WebHost.cs
I'm experimenting with automation to merge branches to prevent drift, so sorry if this change looks funny.
This PR merges commits made on release/2.2 by the following committers:
* @Tratcher
=> [automated] Merge branch 'release/2.2' => 'master'

build/dependencies.props, src/Microsoft.AspNetCore/Microsoft.AspNetCore.csproj, src/Microsoft.AspNetCore/WebHost.cs, test/Microsoft.AspNetCore.FunctionalTests/Microsoft.AspNetCore.FunctionalTests.csproj, test/Microsoft.AspNetCore.FunctionalTests/WebHostFunctionalTests.cs, test/TestSites/CreateDefaultBuilderApp/CreateDefaultBuilderApp.csproj
https://github.com/aspnet/MetaPackages/issues/279
cc @shirhatti
=> Add UseIIS to CreateDefaultBuilder

test/TestSites/CreateDefaultBuilderApp/CreateDefaultBuilderApp.csproj
https://github.com/aspnet/IISIntegration/pull/1129
=> Remove ANCM reference from test site
